language: scala
scala:
  - 2.10.5
jdk:
  - oraclejdk8
sudo: false
script:
  - sbt -jvm-opts travis/jvmopts.compile compile
  - travis_wait 40 sbt -jvm-opts travis/jvmopts.test test > /tmp/sbt.out 2>&1
